self_play:
  tournament_runner_path: "path/to/fastchess.exe"
  engine1_path: "path/to/engine1.exe"
  engine2_path: "path/to/engine2.exe"
  opening_book_path: "data/01_opening_books/4moves_noob.epd"
  opening_book_fmt: "epd"
  tc: "10+0.1"
  rounds: 10
  concurrency: 4
  output_dir: "data/02_pgns"

pgn_to_fen_with_wdl:
  pgn_dir: "data/02_pgns"
  output_dir: "data/03_raw_fens"
  quite_labelled_output_dir: "data/04_quite_labelled"

create_training_data:
  quite_labelled_dir: "data/04_quite_labelled"
  training_data_output_dir: "data/05_training_data"
  size: 100000
